using System;
using System.Text;

namespace Vent.Core.Updates
{
    /// <summary>
    /// The text of the detached helper that waits for the game to quit, then swaps the install.
    ///
    /// It is a separate pure class so the quoting is unit tested. These scripts delete and
    /// overwrite directories; a path with a space in it that is not quoted correctly (say
    /// "/Applications/My Games/Vent.app") is the one bug here that destroys someone's data.
    /// </summary>
    public static class UpdateScripts
    {
        /// <summary>Single-quote for POSIX sh: wrap in ', and write ' as '\''.</summary>
        public static string ShellQuote(string value)
        {
            if (value == null)
            {
                return "''";
            }

            return "'" + value.Replace("'", "'\\''") + "'";
        }

        /// <summary>
        /// A batch variable assignment, written as <c>set "VAR=value"</c>. The quotes go around the
        /// whole assignment, not the value, so the variable holds a bare path: writing
        /// <c>set VAR="C:\x"</c> instead would store the quote characters and break both
        /// <c>%VAR%</c> in a quoted argument and <c>$env:VAR</c> in the PowerShell call.
        ///
        /// Batch cannot express a literal double quote or a percent sign in a path safely, so those
        /// are rejected rather than mangled into something that deletes the wrong directory.
        /// </summary>
        public static string CmdAssign(string name, string value)
        {
            if (value == null)
            {
                value = string.Empty;
            }

            if (value.IndexOf('"') >= 0 || value.IndexOf('%') >= 0)
            {
                throw new ArgumentException($"Path contains a quote or percent sign, which cmd cannot express safely: {value}");
            }

            return $"set \"{name}={value}\"";
        }

        /// <summary>
        /// macOS: unpack with ditto (System.IO.Compression drops the executable bit and flattens
        /// symlinks, producing a bundle that will not launch), swap the bundle aside rather than
        /// deleting it, and restore it if the copy fails.
        /// </summary>
        public static string MacOs(int pid, string zipPath, string stageDir, string installedApp, string logPath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("#!/bin/bash");
            sb.AppendLine("# Generated by Vent's updater. Safe to delete.");
            sb.AppendLine("set -u");
            sb.AppendLine($"PID={pid}");
            sb.AppendLine($"ZIP={ShellQuote(zipPath)}");
            sb.AppendLine($"STAGE={ShellQuote(stageDir)}");
            sb.AppendLine($"APP={ShellQuote(installedApp)}");
            sb.AppendLine($"LOG={ShellQuote(logPath)}");
            sb.AppendLine("exec >>\"$LOG\" 2>&1");
            sb.AppendLine("echo \"[Updater] helper started $(date)\"");
            sb.AppendLine();
            sb.AppendLine("# Wait for the game to exit; give up rather than hang forever.");
            sb.AppendLine("for _ in $(seq 1 300); do");
            sb.AppendLine("  kill -0 \"$PID\" 2>/dev/null || break");
            sb.AppendLine("  sleep 0.2");
            sb.AppendLine("done");
            sb.AppendLine("if kill -0 \"$PID\" 2>/dev/null; then echo \"[Updater] game still running; aborting\"; exit 1; fi");
            sb.AppendLine("sleep 0.5");
            sb.AppendLine();
            sb.AppendLine("rm -rf \"$STAGE\"");
            sb.AppendLine("mkdir -p \"$STAGE\"");
            sb.AppendLine("ditto -x -k \"$ZIP\" \"$STAGE\" || { echo \"[Updater] unpack failed\"; exit 1; }");
            sb.AppendLine("NEW=\"$STAGE/Vent.app\"");
            sb.AppendLine("[ -d \"$NEW\" ] || { echo \"[Updater] no Vent.app in the archive\"; exit 1; }");
            sb.AppendLine();
            sb.AppendLine("# Move the old bundle aside instead of deleting it, so a failed copy can be undone.");
            sb.AppendLine("rm -rf \"$APP.old\"");
            sb.AppendLine("mv \"$APP\" \"$APP.old\" || { echo \"[Updater] could not move the old app\"; exit 1; }");
            sb.AppendLine("if ! ditto \"$NEW\" \"$APP\"; then");
            sb.AppendLine("  echo \"[Updater] copy failed; rolling back\"");
            sb.AppendLine("  rm -rf \"$APP\"");
            sb.AppendLine("  mv \"$APP.old\" \"$APP\"");
            sb.AppendLine("  exit 1");
            sb.AppendLine("fi");
            sb.AppendLine();
            sb.AppendLine("# Belt and braces: a zip we downloaded ourselves carries no quarantine flag,");
            sb.AppendLine("# but strip it anyway so the relaunch can never trip Gatekeeper.");
            sb.AppendLine("xattr -dr com.apple.quarantine \"$APP\" 2>/dev/null");
            sb.AppendLine("rm -rf \"$APP.old\" \"$STAGE\" \"$ZIP\"");
            sb.AppendLine("echo \"[Updater] installed; relaunching\"");
            sb.AppendLine("open \"$APP\"");
            return sb.ToString();
        }

        /// <summary>
        /// Windows: robocopy /MIR mirrors the new build over the install folder, which also removes
        /// files a new version dropped. The caller must have verified the target really is a Vent
        /// install before this text is ever written.
        /// </summary>
        public static string Windows(int pid, string zipPath, string stageDir, string installDir, string exePath, string rootName, string logPath)
        {
            var sb = new StringBuilder();
            sb.Append("@echo off\r\n");
            sb.Append("rem Generated by Vent's updater. Safe to delete.\r\n");
            sb.Append("setlocal\r\n");
            sb.Append(CmdAssign("PID", pid.ToString(System.Globalization.CultureInfo.InvariantCulture))).Append("\r\n");
            sb.Append(CmdAssign("ZIP", zipPath)).Append("\r\n");
            sb.Append(CmdAssign("STAGE", stageDir)).Append("\r\n");
            sb.Append(CmdAssign("INSTALL", installDir)).Append("\r\n");
            sb.Append(CmdAssign("EXE", exePath)).Append("\r\n");
            sb.Append(CmdAssign("LOG", logPath)).Append("\r\n");
            sb.Append(CmdAssign("NEW", stageDir + "\\" + rootName)).Append("\r\n");
            sb.Append("\r\n");
            sb.Append("rem Wait for the game to exit (60s at most).\r\n");
            sb.Append("set /a TRIES=0\r\n");
            sb.Append(":wait\r\n");
            sb.Append("tasklist /FI \"PID eq %PID%\" 2>nul | find \"%PID%\" >nul\r\n");
            sb.Append("if errorlevel 1 goto ready\r\n");
            sb.Append("set /a TRIES+=1\r\n");
            sb.Append("if %TRIES% GEQ 60 (echo [Updater] game still running; aborting>>\"%LOG%\" & exit /b 1)\r\n");
            sb.Append("timeout /t 1 /nobreak >nul\r\n");
            sb.Append("goto wait\r\n");
            sb.Append("\r\n");
            sb.Append(":ready\r\n");
            sb.Append("if exist \"%STAGE%\" rmdir /s /q \"%STAGE%\"\r\n");
            sb.Append("mkdir \"%STAGE%\"\r\n");
            sb.Append("powershell -NoProfile -NonInteractive -Command \"Expand-Archive -LiteralPath $env:ZIP -DestinationPath $env:STAGE -Force\">>\"%LOG%\" 2>&1\r\n");
            sb.Append("if not exist \"%NEW%\\Vent.exe\" (echo [Updater] archive did not contain Vent.exe>>\"%LOG%\" & exit /b 1)\r\n");
            sb.Append("\r\n");
            sb.Append("robocopy \"%NEW%\" \"%INSTALL%\" /MIR /NFL /NDL /NJH /NJS /R:2 /W:1 >>\"%LOG%\" 2>&1\r\n");
            sb.Append("rem robocopy exits 0-7 for success; 8 and above is a real failure.\r\n");
            sb.Append("if %ERRORLEVEL% GEQ 8 (echo [Updater] mirror failed>>\"%LOG%\" & exit /b 1)\r\n");
            sb.Append("\r\n");
            sb.Append("rmdir /s /q \"%STAGE%\"\r\n");
            sb.Append("del /q \"%ZIP%\"\r\n");
            sb.Append("echo [Updater] installed; relaunching>>\"%LOG%\"\r\n");
            sb.Append("start \"\" \"%EXE%\"\r\n");
            sb.Append("endlocal\r\n");
            return sb.ToString();
        }
    }
}
